/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes/index'
import { Route as SessionsNewRouteImport } from './routes/sessions/new'
import { Route as QuizzesNewRouteImport } from './routes/quizzes/new'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminInvitesRouteImport } from './routes/admin/invites'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions/$sessionId/index'
import { Route as SessionsSessionIdPlayRouteImport } from './routes/sessions/$sessionId/play'
import { Route as SessionsSessionIdMasterRouteImport } from './routes/sessions/$sessionId/master'
import { Route as SessionsSessionIdJoinRouteImport } from './routes/sessions/$sessionId/join'
import { Route as SessionsSessionIdBoardRouteImport } from './routes/sessions/$sessionId/board'
import { Route as QuizzesQuizIdEditRouteImport } from './routes/quizzes/$quizId/edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesNewRoute = QuizzesNewRouteImport.update({
  id: '/quizzes/new',
  path: '/quizzes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/sessions/$sessionId/',
  path: '/sessions/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdPlayRoute = SessionsSessionIdPlayRouteImport.update({
  id: '/sessions/$sessionId/play',
  path: '/sessions/$sessionId/play',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdMasterRoute = SessionsSessionIdMasterRouteImport.update({
  id: '/sessions/$sessionId/master',
  path: '/sessions/$sessionId/master',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdJoinRoute = SessionsSessionIdJoinRouteImport.update({
  id: '/sessions/$sessionId/join',
  path: '/sessions/$sessionId/join',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdBoardRoute = SessionsSessionIdBoardRouteImport.update({
  id: '/sessions/$sessionId/board',
  path: '/sessions/$sessionId/board',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdEditRoute = QuizzesQuizIdEditRouteImport.update({
  id: '/quizzes/$quizId/edit',
  path: '/quizzes/$quizId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/sessions/$sessionId/board': typeof SessionsSessionIdBoardRoute
  '/sessions/$sessionId/join': typeof SessionsSessionIdJoinRoute
  '/sessions/$sessionId/master': typeof SessionsSessionIdMasterRoute
  '/sessions/$sessionId/play': typeof SessionsSessionIdPlayRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/sessions/$sessionId/board': typeof SessionsSessionIdBoardRoute
  '/sessions/$sessionId/join': typeof SessionsSessionIdJoinRoute
  '/sessions/$sessionId/master': typeof SessionsSessionIdMasterRoute
  '/sessions/$sessionId/play': typeof SessionsSessionIdPlayRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/settings': typeof SettingsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/sessions/new': typeof SessionsNewRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/sessions/$sessionId/board': typeof SessionsSessionIdBoardRoute
  '/sessions/$sessionId/join': typeof SessionsSessionIdJoinRoute
  '/sessions/$sessionId/master': typeof SessionsSessionIdMasterRoute
  '/sessions/$sessionId/play': typeof SessionsSessionIdPlayRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/settings'
    | '/admin/invites'
    | '/auth/login'
    | '/auth/register'
    | '/quizzes/new'
    | '/sessions/new'
    | '/quizzes/'
    | '/api/auth/$'
    | '/quizzes/$quizId/edit'
    | '/sessions/$sessionId/board'
    | '/sessions/$sessionId/join'
    | '/sessions/$sessionId/master'
    | '/sessions/$sessionId/play'
    | '/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/settings'
    | '/admin/invites'
    | '/auth/login'
    | '/auth/register'
    | '/quizzes/new'
    | '/sessions/new'
    | '/quizzes'
    | '/api/auth/$'
    | '/quizzes/$quizId/edit'
    | '/sessions/$sessionId/board'
    | '/sessions/$sessionId/join'
    | '/sessions/$sessionId/master'
    | '/sessions/$sessionId/play'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/settings'
    | '/admin/invites'
    | '/auth/login'
    | '/auth/register'
    | '/quizzes/new'
    | '/sessions/new'
    | '/quizzes/'
    | '/api/auth/$'
    | '/quizzes/$quizId/edit'
    | '/sessions/$sessionId/board'
    | '/sessions/$sessionId/join'
    | '/sessions/$sessionId/master'
    | '/sessions/$sessionId/play'
    | '/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  SettingsRoute: typeof SettingsRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  QuizzesNewRoute: typeof QuizzesNewRoute
  SessionsNewRoute: typeof SessionsNewRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  QuizzesQuizIdEditRoute: typeof QuizzesQuizIdEditRoute
  SessionsSessionIdBoardRoute: typeof SessionsSessionIdBoardRoute
  SessionsSessionIdJoinRoute: typeof SessionsSessionIdJoinRoute
  SessionsSessionIdMasterRoute: typeof SessionsSessionIdMasterRoute
  SessionsSessionIdPlayRoute: typeof SessionsSessionIdPlayRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/new': {
      id: '/quizzes/new'
      path: '/quizzes/new'
      fullPath: '/quizzes/new'
      preLoaderRoute: typeof QuizzesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/play': {
      id: '/sessions/$sessionId/play'
      path: '/sessions/$sessionId/play'
      fullPath: '/sessions/$sessionId/play'
      preLoaderRoute: typeof SessionsSessionIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/master': {
      id: '/sessions/$sessionId/master'
      path: '/sessions/$sessionId/master'
      fullPath: '/sessions/$sessionId/master'
      preLoaderRoute: typeof SessionsSessionIdMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/join': {
      id: '/sessions/$sessionId/join'
      path: '/sessions/$sessionId/join'
      fullPath: '/sessions/$sessionId/join'
      preLoaderRoute: typeof SessionsSessionIdJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/board': {
      id: '/sessions/$sessionId/board'
      path: '/sessions/$sessionId/board'
      fullPath: '/sessions/$sessionId/board'
      preLoaderRoute: typeof SessionsSessionIdBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId/edit': {
      id: '/quizzes/$quizId/edit'
      path: '/quizzes/$quizId/edit'
      fullPath: '/quizzes/$quizId/edit'
      preLoaderRoute: typeof QuizzesQuizIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  SettingsRoute: SettingsRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  QuizzesNewRoute: QuizzesNewRoute,
  SessionsNewRoute: SessionsNewRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  QuizzesQuizIdEditRoute: QuizzesQuizIdEditRoute,
  SessionsSessionIdBoardRoute: SessionsSessionIdBoardRoute,
  SessionsSessionIdJoinRoute: SessionsSessionIdJoinRoute,
  SessionsSessionIdMasterRoute: SessionsSessionIdMasterRoute,
  SessionsSessionIdPlayRoute: SessionsSessionIdPlayRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
